server:
  port: 8082

spring:
  application:
    name: echo-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:echo_db}
    username: ${DB_USER:echo_user}
    password: ${DB_PASSWORD:echo_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.echo.api: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: WARN